### ISSUE TITLE
Please cut new release that includes python3 support.

### ISSUE THREAD

**Issue by wt** [0xGiddi/pymbr#2]
Hey there, thanks for the fix for py3 in #1 . Any chance you're going to cut a new version that declares py3 support in the setup.py? I would love this to be easily pip installable, especially if you've run it on py3 at this point.

**Comment by 0xGiddi** [comment]
I did update the setup.py and create a release for it. But I'm currently having trouble uploading it to the new Pypi servers (I get 500 Internal server error) so it may take me some time to get the latest version on Pypi for a `pip install pymbr`.

**Comment by wt** [comment]
Thanks, you rock!

**Comment by cooperlees** [comment]
Please install the latest version of `twine` to upload to PyPI. I don't believe setuptools works anymore.

**Comment by 0xGiddi** [comment]
I tried that, I installed Twine 1.11.0 and still no go. I have tried various different  tools and configurations and still I receive a non descriptive "500: Internal Server Error".

**Comment by cooperlees** [comment]
Please report the problem here:
https://github.com/pypa/warehouse/issues

**Comment by 0xGiddi** [comment]
@wt Server error issue has been solved with pypi.org so v1.0.3 (the python3 hack) has been released.
Don't forget to use `bytes` instead of `str` if supplying data (suck as partition table data).

This is a very basic module and has not been updated in a long time, If you need a feature or something please feel free to open an issue.

**Comment by wt** [comment]
Thank you for being awesome!
